### ISSUE TITLE
Create How to contribute wiki

### ISSUE THREAD

**Issue by alchuu00** [OpenBCca/airbnb-regulation#27]

**Comment by alchuu00** [comment]
@nam-m @immangat @umsu2 
I've written how to contribute wiki, please review it when you have time. Thanks!

https://github.com/OpenBCca/airbnb-regulation/wiki/How-to-contribute

**Comment by immangat** [comment]
should the branch name also include module? Like ```ingestion_module/feature/description```

**Comment by alchuu00** [comment]
> should the branch name also include module? Like `ingestion_module/feature/description`

That's great suggestion! I didn't think about that.
If everyone else agrees I'll add it to the wiki
