### ISSUE TITLE
Create a Wiki on Style Guide

### ISSUE THREAD

**Issue by alchuu00** [OpenBCca/airbnb-regulation#28]

**Comment by alchuu00** [comment]
I wrote a very short python style guide. Please review it. Thanks!
https://github.com/OpenBCca/airbnb-regulation/wiki/Coding-Style-Guide

**Comment by nam-m** [comment]
@alchuu00 Can you add `ruff` installation using poetry: `poetry add ruff` since we don't use pip in poetry env.
And if devs are in analytics/, they would not need to install

**Comment by alchuu00** [comment]
> @alchuu00 Can you add `ruff` installation using poetry: `poetry add ruff` since we don't use pip in poetry env. And if devs are in analytics/, they would not need to install

@nam-m I addressed your comment and edited the wiki
