### ISSUE TITLE
Define Architecture For Ingestion Module

### ISSUE THREAD

**Issue by umsu2** [OpenBCca/airbnb-regulation#6]
- Define Airbnb Listing Format (contract)
- Define MVP architecture for Airbnb Injestion
- Define Testing strategies.

**Comment by immangat** [comment]
Hi @umsu2 ,

I've created the initial draft on the [Ingestion Module Wiki page](https://github.com/OpenBCca/airbnb-regulation/wiki/Ingestion-Module). Please review it, and provide any feedback or suggestions for improvement.

Thanks.
