### ISSUE TITLE
Define Architecture For Policy Evalution Module

### ISSUE THREAD

**Issue by umsu2** [OpenBCca/airbnb-regulation#7]
- Define Architecture For Policy Evaluation Module
- Define contracts
- Define testing strategies

**Comment by nam-m** [comment]
I made first draft here
https://github.com/OpenBCca/airbnb-regulation/wiki/Policy-Evaulation-Module
still working on architecture so didn't have that yet

**Comment by nam-m** [comment]
The doc is updated with Overview, Detailed Design with architecture diagram, Contracts, and Testing methods
@umsu2 it is ready for review now

**Comment by umsu2** [comment]
looks good, move to done and close the issue
